### ISSUE TITLE
Feature to push comic metadata from existing ComicInfo.xml when there is a comicvine id

### ISSUE THREAD

**Issue by rurickdev** [Metron-Project/metron-tagger#157]
**Is your feature request related to a problem? Please describe.** 
I have many series that where tagged with `comictagger` and have all the metadata fetched from comicvine, when trying to create the `MetronInfo.xml` using `metron-tagger` I get the next message

```
Found ComicVine in 'comic file #001 v1 (2024).cbz' metadata and using that to get the metadata...
No Match for 'comic file #001 v1 (2024).cbz'.
```

and then `metron-tagger` just skips this file and does not create the `MetronInfo.xml` file

**Describe the solution you'd like** 
If the data is already there `metron-tagger` could juts copy it into the `MetronInfo.xml` and push that information to the API db so other people with the same comic can fetch the data online. 

All the automatic uploaded data could be reviewed by the community before being considered thrust worthy

**Describe alternatives you've considered** 
I have considered to create manually add all the series I have on the WebUI that doesn't have a Metron page but the quantity of series is too big to even think on starting it, would be cool if this can be done automatically using `metron-tagger` and reading the already existent `ComicInfo.xml`.

**Additional context** 
Not sure if this is concerned to `metron-tagger` domain or another cli or script that you have

**Comment by bpepple** [comment]
Yeah, so this has been brought up *a lot*. There's a couple of problems with it:

1. **Bad Data**: I've looked a few thousand `ComicInfo.xml` from users a few years back, and also looked at some over the weekend for a new feature that I added to Metron-Tagger over the weekend, and to put it mildly the data in the `ComicInfo.xml` is pretty *terrible* most of the time.
2. **Implementation**: The work involved to implement on Metron DB would be fairly substantial, and given `#1` most likely not worth the effort.
3. **Metron-Tagger**: This would be even *more* work, since you would need to handle mapping of the `ComicInfo.xml` characters, teams, etc. to the corresponding items on Metron to prevent duplicates. Not to mention a lot of other data normalizing that would be needed.

So, given the data is fairly sketchy and the work involved to implement this feature is fairly substantial, I don't see any situation where I'd be willing to do it.
